# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: b692ef88e8d44bfd6f0103f5a6217b234d4bb6aeb49757de9624666520dc15378e74c2bf810cf5de3ee83047b256dc881f0fdb44af1d9393af6e3188b6bd86c8

test:
  secret_key_base: 9f2bccd328adb67a79c81366a2e9242c657af60f81e6188a0235d43f5e6f7c1b321a6ff37893cdcb51176169e3b2f35630e645461aa920736f05aa55e9bab795

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
